---

- name: Create ServiceNOW Ticket
  hosts: localhost
  connection: local
  gather_facts: true
  run_once: true
  collections:
    - servicenow.servicenow
  vars_files:
    - group_vars/credentials.yml

  tasks:
  - include_role:
      name: servicenow_changerequest
